steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_world
  - --region=us-east1
  - --source=pub_sub_write/
  - --trigger-http
  - --runtime=python310
  - --entry-point=hello_world